### PR TITLE
Support Ruby 3

### PR DESCRIPTION
**Pull request by sarahsehr**
* Add support for Ruby 3.0, 3.1, and 3.2
* Appraise Ruby 2.7.5 and 2.7.7
* Drop support for Ruby < 2.7
* Drop support for Rails < 6.1

### CODE REVIEW

**Comment by sarahsehr** [comment]
[Evaluate state of ae_page_objects for Ruby 3 compatibility](https://trello.com/c/gJzhqoVH/1047-evaluate-state-of-aepageobjects-for-ruby-3-compatibility)

**Comment by dtoms** [comment]
What are the coverage metrics from Simplcov?

**Comment by dtoms** [comment]
I believe one of the main concerns from @Diasporism  was that the Ruby3 parameters changes might mean tests pass incorrectly.  I don't see anything specifically addressing that here (not complaining).  Do we still think that might be a valid issue?

**Comment by sarahsehr** [comment]
> What are the coverage metrics from Simplcov?

Are you asking for the numbers or what it does?

**Comment by sarahsehr** [comment]
> I believe one of the main concerns from @Diasporism was that the Ruby3 parameters changes might mean tests pass incorrectly. I don't see anything specifically addressing that here (not complaining). Do we still think that might be a valid issue?

I'm waiting to hear back from @Diasporism of an example test that passed when it should have failed. Based on my understanding of the gem (I've been a consumer for a long time, even if not an expert on the gem), that shouldn't happen.

**Comment by dtoms** [comment]
@sarahsehr the coverage numbers.

**Comment by sarahsehr** [comment]
> @sarahsehr the coverage numbers.

The unit test coverage was ~41%. I looked through the actual files and  all the "covered" lines were just the class and method names, not the bodies. Elvis Restly had removed the integration tests, but I added them back because of that low coverage.

**Comment by sarahsehr** [comment]
All PropertyApp selenium tests are passing against a reference to this branch. Nothing to directly QA.

**Pull request merged**
